### ISSUE TITLE
Very nice visualization!

### ISSUE THREAD

**Issue by Klortho** [fivethirtyeight/guns-data#1]
Is the code for the web app up here on GH, as well?

**Comment by mathisonian** [comment]
Thanks @Klortho, unfortunately we don't typically publish the front-end code for the interactives, but I'm happy to answer any questions about how it works. 

Feel free to email matthew dot conlen at fivethirtyeight

**Comment by Klortho** [comment]
Sure, understandable.

**Comment by Klortho** [comment]
Kudos for putting the data out in the open, though!
